name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Push to Docker Hub
        if: success()
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t your-docker-image-name .
          docker push your-docker-image-name
          
      - name: Merge to main
        if: failure() != true
        uses: pullreminders/merge-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          strategy: merge
          branch: main
          
      - name: Notify on failure
        if: failure() == true
        uses: rtCamp/action-slack-notify@v2
        with:
          status: 'failure'
          author_name: ${{ github.actor }}
          text: "Linting or vulnerability scan failure detected in the CI pipeline."
          color: '#FF0000'
          fields: failure.log
          channel: '#your-slack-channel'
          webhook_url: ${{ secrets.YOUR_SLACK_WEBHOOK_SECRET }}
